### ISSUE TITLE
Include tag always includes the original (english) adoc.

### ISSUE THREAD

**Issue by yoneken** [ciampix/kicad-doc#101]
I confirmed the same issue affects all of non-English languages (fr ,it, ja, pl).

Please check 
https://github.com/ciampix/kicad-doc/blob/master/src/CvPcb/CvPcb.adoc#footprint-library-tables
"include::CvPcb_footprint_libraries_tables.adoc[po4a]" tag cannot include "CvPcb_footprint_libraries_tables**-fr**.adoc" or "CvPcb_footprint_libraries_tables**-it**.adoc"...

**Comment by nickoe** [comment]
Didn't we talk about this earlier @BrianSidebotham ?

**Comment by BrianSidebotham** [comment]
Pull request #102 fixes this issue. Thanks for the report yoneken
