### ISSUE TITLE
CMake Build doesn't build include files

### ISSUE THREAD

**Issue by BrianSidebotham** [ciampix/kicad-doc#51]
At the moment, the CMake build system is broken because it does not deal with asciidoc includes which must be generated for each manual chapter and language.

**Comment by BrianSidebotham** [comment]
Working on this in https://github.com/BrianSidebotham/kicad-doc

**Comment by BrianSidebotham** [comment]
In order to modify the files to correct the include file names it's intended to add a custom target that will run a cmake script to modify the translated file in the binary path. CMake isn't great for this type of work directly in a custom target, so the script is necessary to do this work.

Should work fine though...

**Comment by nickoe** [comment]
(I have still not found the time to look through how it really works yet)  But don't a2x normally handle the includes by itself ?

**Comment by ciampix** [comment]
On Thu, May 21, 2015 at 02:25:04PM -0700, nickoe wrote:
> (I have still not found the time to look through how it really works yet)  But don't a2x normally handle the includes by itself ?

Simple answer: a2x yes, po4a not (I filed a bug but I doubt that it will be taken into account...)

-- 


Marco Ciampa

I know a joke about UDP, but you might not get it.

+------------------------+
| GNU/Linux User  #78271 |
| FSFE fellow       #364 |
+------------------------+

**Comment by BrianSidebotham** [comment]
Nick, Although a2x deals with includes, we need translated versions of the includes and therefore the files get suffixed with the two letter language. Because of that, the includes fail. We need to transform the include filename to the correct name for each language.

**Comment by nickoe** [comment]
Ahh ok, I understand the issue now.
Den 22/05/2015 11.28 skrev "Brian Sidebotham" <notifications@github.com>:

**Comment by BrianSidebotham** [comment]
Just to note: I did decided against modifying the include filename in the source file - which seems a bit awkward (At least, for CMake this is near impossible!). So instead, I re-organised the build so that the original include filenames work okay.

Now CMake generates language directories full of that language's documentation. This seems more succinct anyway.

TODO: CMake can have install components. We should create a component per language so that tarballs can be made for each language easily. Not everyone needs documentation in all languages!

**Comment by nickoe** [comment]
Yeah, I am just building to test it. You might open another issue for that todo item, if you don't intend to fix it immediately.    But how should that work?  Then `make install-pl`?

**Comment by BrianSidebotham** [comment]
Thanks Nick,

Re: TODO: It's something like that yes, otherwise we'll have to do a configure-based language selection. I'll open an issue anyway so that we can keep track of progress and ideas.

**Comment by nickoe** [comment]
I am not exactly sure why, but when I do: `mkdir build; cd build; cmake ..; make DESTDIR=/tmp/foobar/ install;`

I get a dot in the path as: `-- Installing: /tmp/foobar/usr/local/./en/Pl_Editor/pdf/Pl_Editor.pdf`

**Comment by BrianSidebotham** [comment]
Probably because the install paths are relative to the root install folder, so I always start with `./` which is fine because `/tmp/foobar/usr/local/./en/Pl_Editor/pdf/Pl_Editor.pdf` is exactly equivalent to `/tmp/foobar/usr/local/en/Pl_Editor/pdf/Pl_Editor.pdf`

So it can be safely ignored.
