### ISSUE TITLE
CMake Builds always packages all languages

### ISSUE THREAD

**Issue by BrianSidebotham** [ciampix/kicad-doc#58]
With the CMake build system, when packaging via `make package` all languages are included; There's no possibility to only build a package for a single language.

**Comment by BrianSidebotham** [comment]
Actually, I think it makes sense to configure a single language build and then use the standard `make package` method of rolling a tarball.

Working on that now.

Should we stick with both .zip and .tar.gz or just pick one and neuter the other for now?

**Comment by nickoe** [comment]
If it is not a big deal to support both, I think we should stick with both,
but it is not critical in my mind.
Den 25/05/2015 23.06 skrev "Brian Sidebotham" <notifications@github.com>:

**Comment by BrianSidebotham** [comment]
np :)
